#pragma config(UserModel, "37T-Robot-2.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "37T-Functions.h"

task main()
{
forward(1200);
turnLeft(500);
back(2300);
wait1Msec(9999999999999999999);

}
