#pragma config(UserModel, "37T-Robot-2.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "37T-Functions.h"


task main()
{
	while(true){
		if(isColorB(mColor)){
			setDrive(127, 87);
		} else {
			setDrive(87, 127);
		}
		delay(25);
	}
}
