#pragma config(UserModel, "37T-Robot-2.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "37T-Functions.h"

task main()
{
	flipperUp(100);
	strafeLeft(500);
	strafeTillLine(127,mColor);
	strafeRight(0);
	armDown(1200);
	forward(1800);//pick up first 2
	armUp(500);
	back(1200);
	armUp(1200);//Colects
	strafeLeft(500);
	strafeTillLine(127, mColor);
	strafeRight(350);
	turnLeft(85);
	armDown(975);
	followLine(127,1200);//pick up second 2 (atempt 1)
	turnRight(500);//adjust
	forward(600);//pick up second 2 (atempt 2)
	armUp(850);
	flipperUp(200);
	turnRight(55);
	back(700);
	strafeTillLine(-127, oColor);
	strafeLeft(300);
	back(5750);//Over the ramp
	forward(500);
	strafeTillLine(127,mColor);
	strafeRight(200);
	back(700);
	flipperUp(600);//Score 2 balls
	wait1Msec(500);
	flipperDown(500);
	armUp(1200);
	armDown(1000);
	forward(520);
	strafeRight(1100);
	back(700);
	flipperUp(600);//Score other 2 balls
	wait1Msec(500);
	flipperDown(600);
}// end main
