#pragma config(UserModel, "C:/Users/rstudent/Documents/37T-Robot-2.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "37T-Functions.h"


task main()
{
	while(true){
		int c = getColorGrayscale(mColor);

		displayBigTextLine(1, "%d", c);
		delay(50);
		eraseDisplay();
	}
}
