#pragma config(Sensor, port7,  mColor,         sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  oColor,         sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          Arm,           tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          Strafe,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         Flipper,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){}
