#pragma config(Sensor, port5,  TouchLED,       sensorNone)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          Flipper,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         Arm,           tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int threshold = 15;    //Deadband %
	static int leftSpeed = 0;   //left joystick input
	static int rightSpeed = 0;  //right joystick input
	int limit =300;


  resetMotorEncoder(Arm);
	while(true)
	{
		leftSpeed = (getJoystickValue(ChA));
		rightSpeed = (getJoystickValue(ChD));

		int ArmAngle=getMotorEncoder(Arm);
		displayTextLine(3, "Degree: %d", ArmAngle);

		if(leftSpeed > threshold || leftSpeed < -threshold)  // check left side to deadband
		{
			setMotorSpeed(leftMotor, leftSpeed);

		}
		else
		{
			setMotorSpeed(leftMotor, 0);
		}

		if(rightSpeed > threshold || rightSpeed < -threshold)// check right side to deadband
		{
			setMotorSpeed(rightMotor, rightSpeed);
		}
		else
		{
			setMotorSpeed(rightMotor, 0);
		}

		// Arm
		if(getJoystickValue(BtnLUp) == 1&&ArmAngle<limit)// check arm limit to soft stop
		{

				setMotorSpeed(Arm,  127);
		}


		//Arm
		else if(getJoystickValue(BtnLDown) == 1)
		{

				if(ArmAngle>0)
				{
					setMotorSpeed(Arm, -127);
			  }
					else
					{
						setMotorSpeed(Arm,  0);

			    }
			 }
		   else
		   {
		     setMotorSpeed(Arm,  0);
		   }


			//Flipper
		if(getJoystickValue(BtnRDown) == 1)
		{
				setMotorSpeed(Flipper,  127);
		}

		else if(getJoystickValue(BtnRUp) == 1&&ArmAngle<10)
		{
			setMotorSpeed(Flipper,  -127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(Flipper,  0);
	}

	}// end while
}// end main
